name: Feature request
description: Suggest an idea that may improve Sevenwiki
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please ensure the following before submitting.
      options:
        - label: I've **checked both [open and recently closed issues](https://github.com/Sevenwiki/issues/issues)** to ensure this feature is not already requested.
          required: true
        - label: This is a **feature request**, not a bug report.
          required: true

  - type: input
    attributes:
      label: Related feature or component
      placeholder: e.g. Markdown Editor, User Profile

  - type: textarea
    attributes:
      label: Describe the feature/enhancement
      description: A clear and concise description of the feature you’d like to see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case / scenario
      description: Describe how this feature would be helpful and the scenarios in which you’d use it.
      placeholder: |
        1. Describe the situation where this feature will be useful.
        2. Explain the improvement it will bring.

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear description of how you expect the feature to work.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or workarounds you’ve considered.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots related to the request.
